"""add hadith_id to user_question_history

Revision ID: 11d984353717
Revises: 
Create Date: 2025-07-09 22:27:55.836500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11d984353717'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_question_history_id'), table_name='user_question_history')
    op.drop_table('user_question_history')
    op.drop_index(op.f('ix_user_favorite_hadiths_id'), table_name='user_favorite_hadiths')
    op.drop_table('user_favorite_hadiths')
    op.drop_index(op.f('ix_journey_modules_id'), table_name='journey_modules')
    op.drop_table('journey_modules')
    op.drop_index(op.f('ix_hadiths_id'), table_name='hadiths')
    op.drop_table('hadiths')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_name'), table_name='sources')
    op.drop_index(op.f('ix_sources_type'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('sources',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('sources_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sources_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_sources_type'), 'sources', ['type'], unique=False)
    op.create_index(op.f('ix_sources_name'), 'sources', ['name'], unique=False)
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('questions_source_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('questions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('questions_pkey'))
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_table('hadiths',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('hadiths_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='hadiths_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_hadiths_id'), 'hadiths', ['id'], unique=False)
    op.create_table('journey_modules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('progress', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('journey_modules_pkey'))
    )
    op.create_index(op.f('ix_journey_modules_id'), 'journey_modules', ['id'], unique=False)
    op.create_table('user_favorite_hadiths',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hadith_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hadith_id'], ['hadiths.id'], name=op.f('user_favorite_hadiths_hadith_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_favorite_hadiths_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_favorite_hadiths_pkey'))
    )
    op.create_index(op.f('ix_user_favorite_hadiths_id'), 'user_favorite_hadiths', ['id'], unique=False)
    op.create_table('user_question_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_question_history_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_question_history_pkey'))
    )
    op.create_index(op.f('ix_user_question_history_id'), 'user_question_history', ['id'], unique=False)
    # ### end Alembic commands ###
